version: "3.9"

services:
  code:
    image: codercom/code-server
    restart: unless-stopped
    environment:
      PASSWORD: "password"
    ports:
      - 8080:8080
    volumes:
      - ./project:/root/project