version: '3.9'

services:
  nvim:
    build:
      context: .
      dockerfile: ./dockerfile
      args:
        UID: $UID
        GID: $GID
        UNAME: $UNAME
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 2G
    volumes:
      - ../workspace/:/home/$UNAME/workspace/
    tty: true
    working_dir: /home/$UNAME/workspace/