version: "3.9"

services:

  code:
    image: codercom/code-server
    user: $user
    restart: unless-stopped
    environment:
      PASSWORD: "password"
    ports:
      - 8080:8080
    volumes:
      - ../:/home/$UNAME/codes