from codercom/code-server

arg UNAME
env UNAME ${UNAME}

user root

run usermod -l $UNAME coder && \
  groupmod -n $UNAME coder

run echo "${UNAME}    ALL=(ALL)   NOPASSWD:    ALL" >> /etc/sudoers.d/${UNAME}

user $UNAME