FROM alpine

SHELL ["/bin/ash", "-c"]

RUN apk update && apk --update add \
curl \
gcc \
g++ \
neovim \
python3 \
python3-dev

RUN curl -kL https://bootstrap.pypa.io/get-pip.py | python3
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install neovim

ARG UID
ARG GID
ARG UNAME

ENV UID ${UID}
ENV GID ${GID}
ENV UNAME ${UNAME}

run addgroup -g ${GID} -S ${UNAME}
run adduser -u ${UID} -G ${UNAME} -S ${UNAME}

user ${UNAME}
